### PR TITLE
fix: verifiable relocation trigger

### LINKED ISSUE #2011: Make relocation details verifiable.
Nodes are relocated between sections based on a `ChurnId`. These churn Id's decide two things:
1. which nodes will be relocated to a new section.
2. which section the node will be relocated to

So if they are forgeable, a faulty elder could arbitrarily force any node to relocate to a section of their choice. We need to ensure that this can't happen.

Currently the NodeState struct looks like this:

```
pub struct NodeState {
    peer: Peer,
    state: MembershipState,
    previous_name: Option<XorName>,
}

pub enum MembershipState {
    Joined,
    Left,
    Relocated(RelocationDst), // <-- what we are looking at in this issue
}

pub struct RelocationDst(XorName)
```

We need to replace the RelocationDst with something verifiable, like a RelocationTrigger that holds the verifiable event that triggered this relocation.

The end state would look something like this:

```
pub struct NodeState {
    peer: Peer,
    state: MembershipState,
    previous_name: Option<XorName>,
}

pub enum MembershipState {
    Joined,
    Left,
    Relocated(RelocationTrigger>),
}

pub struct RelocateTrigger(Decision<NodeState>)

impl RelocateTrigger {
    fn dst(&self) -> XorName; // derived from signed node state
}
```

### PR DESCRIPTION
**Pull request by b00f**
## Summary

In this PR:
- `CurhnId` moved to network_knowledge
- `RelocationDst` replaced with `RelocationTrigger` 
- `RelocationTrigger` has decision and therefore it is verifiable
- Test are updated to use trigger (result of decision)

## Issues

It fixes #2011 

## TODO

Perhaps we can mock the decision (consensus) for faster tests.

### CODE REVIEW

File: sn_node/src/node/messaging/relocation.rs [hunk 1]
```diff
@@ -316,8 +318,16 @@ mod tests {
                 }
             })
         {
-            initialize_relocation(dispatcher, relocation_node_old_name, prefix1, msg_counter)
-                .await?;
+            let sk_set = env.get_secret_key_set(prefix1, None);
+            let age = relocation_node_old_name[XOR_NAME_LEN - 1];
+            let relocation_trigger = create_relocation_trigger(&sk_set, age + 1);
```
Comment (b00f) [inline sn_node/src/node/messaging/relocation.rs:323]: @joshuef here we create relocation trigger. It is repeated for all nodes (17 nodes) since it is brute forcing to create trigger, the test is slow.

Comment (joshuef) [reply sn_node/src/node/messaging/relocation.rs:323]: Ah right. This slowness is coming from the PR, right? Is there another way to do this rather than brute forcing? Passing the relocation trigger in after one run perhaps?

Comment (b00f) [reply sn_node/src/node/messaging/relocation.rs:323]: Not sure how we can fix it. Mocking decision looks the good option here, but needs refactoring the code.

Comment (joshuef) [reply sn_node/src/node/messaging/relocation.rs:323]: why does it need to happen for all 17 nodes? Can't we do it once in the test and then pass it in?

Comment (b00f) [reply sn_node/src/node/messaging/relocation.rs]: @joshuef I moved it out of the loop, now is faster.

**Comment by joshuef** [comment]
bors try

File: sn_interface/src/network_knowledge/node_state/relocation.rs [hunk 2]
```diff
@@ -6,7 +6,7 @@
 // KIND, either express or implied. Please review the Licences for the specific language governing
 // permissions and limitations relating to use of the SAFE Network Software.
 
-use std::fmt::{self, Formatter};
+use std::fmt::{self, Display, Formatter};
```
Comment (oetyng) [inline sn_interface/src/network_knowledge/node_state/relocation.rs:9]: Nitpick:

Third party libs would - by our loose and (afaik) not entirely verbalized conventions - form a section of lines furthest down.
On top of that is our `sn_*` libs, then `crate`, `super` and lastly `self`.

So that basically means the usings are structured according to how close to this file they are.

```
use self::Abc;
use self::Bce;

use super::Cde;
use super::Def;

use crate::Efg;
use crate::Fgh;

use sn_ghi::Hij;
use sn_ijk::Jkl;

use std::fmt::Display;
use xor_name::XorName;
```

(Note that, as can be seen by the above use of `xor_name`, all non `sn_*` libs are treated as third party, even though they are created/maintained by maidsafe.)

Comment (oetyng) [reply sn_interface/src/network_knowledge/node_state/relocation.rs:9]: Usually when there is just one `super` for example, I'd not add an empty line between that and a `crate` use.

Usually we seem to not combine the `crate` or `super` usings, and I think having them separate improves readability.

All other though are combined. I.e.:
```
use serde::{Deserialize, Serialize};
```

But remember these are quite loose conventions, and I would guess that not everyone think it matters much, down to the details described above. Those are a mix of my preferences and what I think is followed by most.

Usings in tests are even more loosely approached generally.

File: sn_interface/src/network_knowledge/node_state/relocation.rs [hunk 3]
```diff
@@ -15,20 +15,56 @@ use crate::network_knowledge::{Error, Result};
...
     /// We are relocating to the section that matches `dst_name`.
-    pub fn new(dst_name: XorName) -> Self {
-        Self(dst_name)
+    pub fn new(decision: Decision<NodeState>) -> Self {
+        Self(decision)
     }
 
-    pub fn name(&self) -> &XorName {
-        &self.0
+    ///
```
Comment (oetyng) [inline sn_interface/src/network_knowledge/node_state/relocation.rs:45]: Maybe add a few words here.

File: sn_interface/src/network_knowledge/node_state/relocation.rs [hunk 4]
```diff
@@ -15,20 +15,56 @@ use crate::network_knowledge::{Error, Result};
...
+        for sig in self.0.proposals.values() {
+            content_parts.push(sig.to_bytes().to_vec());
+        }
+
+        XorName::from_content_parts(
+            Vec::from_iter(content_parts.iter().map(|v| v.as_slice())).as_slice(),
+        )
+    }
+
+    ///
```
Comment (oetyng) [inline sn_interface/src/network_knowledge/node_state/relocation.rs:58]: Maybe add a few words here.

File: sn_node/src/node/relocation.rs [hunk 5]
```diff
@@ -236,6 +181,7 @@ mod tests {
     // from an unspecified random data using an unspecified random `SecretKey`. That is OK because
     // the relocation algorithm doesn't care about whether the signature is valid. It only
     // cares about its number of trailing zeros.
+    #[allow(dead_code)]
     fn signature_with_trailing_zeros(trailing_zeros_count: u32) -> bls::Signature {
```
Comment (oetyng) [inline sn_node/src/node/relocation.rs:185]: Do we need to keep this fn?

File: sn_node/src/node/relocation.rs [hunk 6]
```diff
@@ -253,6 +199,7 @@ mod tests {
         })
     }
 
+    #[allow(dead_code)]
     fn gen_signature_with_trailing_zeros(trailing_zeros_count: u32) -> bls::Signature {
```
Comment (oetyng) [inline sn_node/src/node/relocation.rs:203]: Do we need to keep this fn?

File: sn_interface/src/network_knowledge/mod.rs [hunk 7]
```diff
@@ -598,10 +599,35 @@ fn create_first_sig<T: Serialize>(
     })
 }
 
+// Returns the number of trailing zero bits of the bytes slice.
+pub fn trailing_zeros(bytes: &[u8]) -> u32 {
```
Comment (oetyng) [inline sn_interface/src/network_knowledge/mod.rs:603]: Is there any special reason this is moved to `network_knowledge`?

**Review by oetyng — APPROVED** [review]
LGMT just a few questions and minor points.

File: sn_node/src/node/flow_ctrl/tests/cmd_utils.rs [hunk 8]
```diff
@@ -162,7 +162,12 @@ impl<'a> ProcessAndInspectCmds<'a> {
     }
 
     pub(crate) async fn next(&mut self) -> crate::node::error::Result<Option<&Cmd>> {
-        let mut next_index = self.index_inspected + 1;
+        let mut next_index = if self.index_inspected == usize::MAX {
```
[the remark this answers is not in the document]
Comment (b00f) [reply sn_node/src/node/flow_ctrl/tests/cmd_utils.rs:165]: Nope, unless we define `isize` and set it to -1

File: sn_interface/src/network_knowledge/mod.rs (hunk 7 above)
Comment (b00f) [reply sn_interface/src/network_knowledge/mod.rs:603]: Otherwise we need to duplicate the code. It is used by `relocation_check` in `network_knowledge`. Any suggestion?

File: sn_node/src/node/relocation.rs (hunk 5 above)
Comment (b00f) [reply sn_node/src/node/relocation.rs:185]: Yes, unless we delete them, they are not used by any other modules.

File: sn_interface/src/network_knowledge/node_state/relocation.rs (hunk 2 above)
Comment (b00f) [reply sn_interface/src/network_knowledge/node_state/relocation.rs:9]: Done

File: sn_interface/src/network_knowledge/test_utils.rs [hunk 9]
```diff
@@ -274,3 +274,29 @@ where
...
+) -> (RelocationTrigger, Decision<NodeState>) {
+    use super::relocation_check;
+
+    loop {
+        let node_state = NodeState::joined(gen_peer(MIN_ADULT_AGE), Some(xor_name::rand::random()));
+        let decision = section_decision(sk_set, node_state.clone());
+        let relocation_trigger = RelocationTrigger::new(decision.clone());
+        let churn_id = relocation_trigger.churn_id();
+
+        if relocation_check(age, &churn_id) && !relocation_check(age + 1, &churn_id) {
```
[the remark this answers is not in the document]
Comment (b00f) [reply sn_interface/src/network_knowledge/test_utils.rs:298]: I am not sure why. This code is only uses by tests, probably better to keep it as it is.

File: sn_interface/src/network_knowledge/node_state/relocation.rs (hunk 3 above)
Comment (b00f) [reply sn_interface/src/network_knowledge/node_state/relocation.rs]: Done, Let me know if it needs to be amended

File: sn_interface/src/network_knowledge/node_state/relocation.rs (hunk 4 above)
Comment (b00f) [reply sn_interface/src/network_knowledge/node_state/relocation.rs]: Done, Let me know if it needs to be amended

File: sn_interface/Cargo.toml [hunk 10]
```diff
@@ -30,18 +30,18 @@ itertools = "~0.10.0"
...
+rand-07 = { package = "rand", version = "0.7.3" }                                    # required till ed25519-dalek upgrades to rand v0.8
 rayon = "1.5.1"
 rmp-serde = "1.0.0"
 self_encryption = "~0.27.5"
 serde = { version = "1.0.111", features = ["derive", "rc"] }
 serde_bytes = "~0.11.5"
 serde_json = "1.0.53"
 signature = "1.1.10"
-sn_consensus = "3.2.1"
+sn_consensus = { version = "3.2", git = "https://github.com/maidsafe/sn_consensus" }
```
Comment (davidrusu) [inline sn_interface/Cargo.toml:44]: let's drop the git reference now that sn_consensus is published.
```suggestion
sn_consensus = "3.2.1"
```

File: sn_interface/src/network_knowledge/test_utils.rs (hunk 9 above)
[the remark this answers is not in the document]
Comment (davidrusu) [reply sn_interface/src/network_knowledge/test_utils.rs:297]: I think the idea is that this helper generates a relocation trigger that will only relocate nodes of a specific age i.e. age=4

Useful in tests to target a specific node.

File: sn_node/Cargo.toml [hunk 11]
```diff
@@ -55,7 +60,7 @@ rand-07 = { package = "rand", version = "~0.7.3" }
 rayon = "1.5.1"
 rmp-serde = "1.0.0"
 self_encryption = "~0.27.5"
-sn_consensus = "3.2.1"
+sn_consensus = { version = "3.2", git = "https://github.com/maidsafe/sn_consensus" }
```
Comment (davidrusu) [inline sn_node/Cargo.toml:63]: ditto, drop the git ref
```suggestion
sn_consensus = "3.2.1"
```

File: sn_node/src/node/flow_ctrl/tests/cmd_utils.rs (hunk 8 above)
[the remark this answers is not in the document]
Comment (davidrusu) [reply sn_node/src/node/flow_ctrl/tests/cmd_utils.rs:165]: Try `let mut next_index = self.index_inspected.wrapping_add(1);`

See docs: https://doc.rust-lang.org/std/primitive.u64.html#method.wrapping_add

[the remark this answers is not in the document]
Comment (davidrusu) [reply sn_node/src/node/flow_ctrl/tests/cmd_utils.rs:165]: Sorry, I read the code further and I think this introduces a bug no?

If `index_inspected` is usize::MAX, it'll be set to `0` here. Then on line [174](https://github.com/maidsafe/safe_network/pull/2094/files#diff-150691660f12f76fba4707f7d381fae6aeee5aabcc1e2aea83832f1e9edc8c72R179) below, it subtracts 1 so we underflow. I don't think that's what's intended.

File: sn_node/src/node/relocation.rs (hunk 5 above)
Comment (b00f) [reply sn_node/src/node/relocation.rs:185]: @joshuef I tried `cfg(test)` but I got this error on clippy: 
```
function `signature_with_trailing_zeros` is never used
```

File: sn_node/src/node/flow_ctrl/tests/cmd_utils.rs (hunk 8 above)
[the remark this answers is not in the document]
Comment (b00f) [reply sn_node/src/node/flow_ctrl/tests/cmd_utils.rs]: @davidrusu done

File: sn_node/src/node/relocation.rs (hunk 5 above)
Comment (davidrusu) [reply sn_node/src/node/relocation.rs:185]: Yeah, if it's no longer used, remove it

**Review by davidrusu — APPROVED** [review]
Looks like you've got some conflicts again, and you can remove those unused functions with the `allow(dead)`.

Besides that, looks great 👍

**Review by davidrusu — APPROVED** [review]

**Review by joshuef — APPROVED** [review]
approved after rebase 👍

**Review by joshuef — APPROVED** [review]
